#ifndef TOYOS_MULTIBOOT2_CONSTANTS_H_
#define TOYOS_MULTIBOOT2_CONSTANTS_H_

#define MULTIBOOT2_HEADER_MAGIC 0xE85250D6
#define MULTIBOOT2_ARCHITECTURE_I386 0

#endif /* TOYOS_MULTIBOOT2_CONSTANTS_H_ */
